mq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
debug: false
subscribers:
  "demo":
    secret: YOURSECRET
    channels:
      - exchange: "demo"
        type: "topic"
        routing_keys:
          - topic1
          - topic2
        callback:
          url: "http://demo.local/api"
          method: "demo/getNotified"
