mq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
debug: false
subscribers:
  demo:
    secret: YOURSECRET
    channels:
      - exchange: rpc
        type: topic
        routing_keys:
          - topic1
          - topic2
        callback:
          type: http-jsonrpc
          url: http://demo.local/api
          method: demo/getNotified
      - exchange: beanstalk
        type: topic
        routing_keys:
          - topic1
          - topic2
        callback:
          type: beanstalk
          url: 127.0.0.1:11300
          tube: tubeName
      - exchange: socket.io
        type: topic
        routing_keys:
          - topic1
          - topic2
        callback:
          type: socket.io
          url: http://127.0.0.1:7890
          event: eventName
